services:
  ponger:
    build: ./ponger
    environment:
      - PORT=8001

  proxy1:
    build: ./proxy1
    environment:
      - PORT=8080
    depends_on:
      - ponger

  proxy2:
    build: ./proxy2
    environment:
      - PORT=8080
    depends_on:
      - ponger

  pinger:
    build: ./pinger
    depends_on:
      - proxy1
      - proxy2
